### ISSUE TITLE
ValueError in scrub_deveny_pickup

### ISSUE THREAD

**Issue by philip-muirhead** [LowellObservatory/LDTObserverTools#9]
I get the following error when running scrub_deveny_pickup:

Processing frame 20231110.0090.fits
   --> FFT-predicted pixel period: 157.2 pix
 * No object model extracted.  Moving along...
Fitting sinusoids to each line in the image...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 508/508 [09:04<00:00,  1.07s/row]
   --> Mean fit pixel period: 157.8 pix
Refitting lines with poor fit in first pass...
  0%|                                                                                                                                                                       | 0/453 [00:00<?, ?row/s]Traceback (most recent call last):
  File "/opt/miniconda3/envs/obstools/bin/scrub_deveny_pickup", line 8, in <module>
    sys.exit(ScrubDevenyPickup.entry_point())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/obstools/utils.py", line 537, in entry_point
    sys.exit(cls.main(args))
             ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/obstools/scrub_deveny_pickup.py", line 1684, in main
    iterative_pypeit_clean(
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/obstools/scrub_deveny_pickup.py", line 221, in iterative_pypeit_clean
    resid_fitc = fit_lines(
                 ^^^^^^^^^^
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/obstools/scrub_deveny_pickup.py", line 733, in fit_lines
    closest_idx = ind_goodrms[np.argmin(np.abs(img_row - ind_goodrms))]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1325, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/obstools/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence
  0%|                                                                                                                                                                       | 0/453 [00:00<?, ?row/s]

**Comment by tbowers7** [comment]
I've replicated your error, and am looking into what to do about it.

Thanks for beta-testing and finding the various edge cases.
